version: "3.3"
services:
    webserver:
        build:
            context: ./bin/webserver
            args:
                uid: ${UID}
                username: 'devuser'
        container_name: 'yt-webserver'
        restart: 'always'
        ports:
            - '25:25'
            - '80:80'
            - '443:443'
        links:
            - mariadb
        volumes:
            - ${DOCUMENT_ROOT-./www}:/var/www/html
            - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
            - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
            - ${LOG_DIR-./logs/apache2}:/var/log/apache2/
        depends_on:
            - mariadb
        networks:
            static-network:
                ipv4_address: 172.18.0.10
    mariadb:
        image: mariadb/server
        container_name: 'yt-mariadb'
        restart: 'always'
        ports:
            - '3306:3306'
        volumes:
            - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
            - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: yourtube
            MYSQL_USER: yourtube
            MYSQL_PASSWORD: yourtube
        networks:
            static-network:
                ipv4_address: 172.18.0.20
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: 'yt-myadmin'
        ports:
            - '8080:80'
        links:
            - mariadb
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
        volumes:
            - /sessions
        depends_on:
            - mariadb
        networks:
            static-network:
                ipv4_address: 172.18.0.30
networks:
    static-network:
        ipam:
            config:
                - subnet: 172.18.0.0/16
