version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    image: web:latest
    container_name: web
    depends_on:
      - db
    volumes:
      - ./www:/var/www/html/
      - ./logs:/var/log/apache2/

    links:
      - db:db
    networks:
      static-network:
        ipv4_address: 172.18.0.4
  db:
    image: mariadb/server
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: root

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.18.0.0/16
